# This is a basic workflow that is manually triggered

name: Release tag

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get latest RC tag
        id: latest_tag
        run: |
          git fetch --tags
          echo ::set-output name=tag::$(git describe --tags --match "RC*" $(git rev-list --tags --max-count=1))

      - name: Create SR tag
        run: |
          SR_TAG=$(echo "${{ steps.latest_tag.outputs.tag }}" | sed -e 's/^RC/SR/')
          git tag $SR_TAG
          git push origin $SR_TAG
